

local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()

local Window = Library.CreateLib("Chronium", "Ocean")
local Info = Window:NewTab("Information")
local Main = Window:NewTab("Main")
local Credits = Window:NewTab("Credits")



local Info = Info:NewSection("WARNING: Use this script in a alternative account!")
local Main = Main:NewSection("Bypassed words")


Info:NewKeybind("V To keybind", "", Enum.KeyCode.V, function()
	Library:ToggleUI()
end)



Main:NewButton("Say fuck", "say fuck", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("𐌜 f𐌜𐌜 u𐌜 c𐌜 k", "All")
end)
Main:NewButton("Say sex", "say sex", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("s ͅ𐌜ex","All")
end)
Main:NewButton("Say porn", "say porn", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("p ͅ𐌜orn","All")
end)
Main:NewButton("Say horny", "say horny", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("h ͅ𐌜orny","All")
end)
Main:NewButton("Say cock", "say cock", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("c ͅ𐌜o  ͅ𐌜cky","All")
end)
Main:NewButton("Say penis", "say penis", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("p ͅ𐌜en ͅ𐌜is","All")
end)
Main:NewButton("Say dick", "say dick", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("d 𐌜iͅ c ͅ𐌜 ͅ𐌜k","All")
end)
Main:NewButton("Say ass", "say ass", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ͅ𐌜ass ͅ𐌜","All")
end)
Main:NewButton("Say pussy", "say pussy", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("p ͅ𐌜ussy","All")
end)
Main:NewButton("Say vagina", "say vagina", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("v ͅ𐌜agina","All")
end)
Main:NewButton("Say cum", "say cum", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("c ͅ𐌜um","All")
end)
Main:NewButton("Say the n-word", "say ni-", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("n ͅ𐌜igg ͅ𐌜a","All")
end)
Main:NewButton("Say the n-word 2", "say ni-", function()
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("n ͅ𐌜igg ͅ𐌜er")
end)

Credits:Label("Script made by chronium#4096")
Main:NewButton("Copy the discord invite", "dopies the discord server's ivnite", function()
    setclipboard("https://discord.gg/HDMQV9nBKx")
end)
Credits:Label("UI library credited to Kavo Library")
Credits:Label("thx for using chronium hub :-)")
